server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /
    session:
      timeout: 30m

spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:///C:/upload/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chami_dev
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-request-size: 3MB

logging:
  level:
    root: debug
